apiVersion: v1
kind: Service
metadata:
  name: drone-server
spec:
  type: NodePort
  ports:
    - name: drone
      port: 8000
      protocol: TCP
      targetPort: 8000
      nodePort: 30567
  selector:
    app: drone-server
